---
server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

logging:
  level: INFO
  loggers:
    com.yaro: DEBUG
  appenders:
  - type: console
    threshold: ALL
    timeZone: America/Los_Angeles
    logFormat: "####%d{yyyy-MM-dd HH:mm:ss.SSS} %level %thread %msg%n"
